#!/usr/bin/env bash

#/ command: rundeck-project:acls-list: "list the acls in the project"
#/ usage: rerun rundeck-project:acls-list  --project <>  --url <$RUNDECK_URL>  --username <$RUNDECK_USER> [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: PROJECT URL USERNAME PASSWORD APIKEY

. $RERUN_MODULE_DIR/lib/functions.sh acls-list || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}


set -o errexit -o nounset -o pipefail


rerun_options_parse "$@"


#
# Read authentication credentials
#
rundeck_authenticate -u "$URL" -U "$USERNAME" -p "${PASSWORD:-}" -k "${APIKEY:-}"


CURL_OUT=$(mktemp -t curl.out.XXXXXXXXXX)
trap 'rm $CURL_OUT' EXIT; # cleanup on exit

if ! http_code=$(rundeck_curl -w "%{http_code}" -H "Accept: application/xml" \
	-X GET ${URL}/api/14/project/$PROJECT/acl/ -o $CURL_OUT)
then
	rerun_die 3 "curl request failed (exit code: $?)"
fi	

case ${http_code:-} in
   	200) : ;; # successful
	* ) rerun_die 3 "API error: ${URL}/api/14/project/$PROJECT/acl/"
esac  

if ! xmlstarlet sel -t -m '/resource/contents/resource' -v @path -n $CURL_OUT
then
	rerun_log debug "No ACL policies exist for project: $PROJECT"
fi


# Done. Exit with last command exit status.
exit $?

