#!/usr/bin/env bash

#/ command: rundeck-project:acls-list: "list the acls in the project"
#/ usage: rerun rundeck-project:acls-list  --project <>  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: PROJECT URL USERNAME PASSWORD APIKEY

. $RERUN_MODULE_DIR/lib/functions.sh acls-list || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}


set -o errexit -o nounset -o pipefail


rerun_options_parse "$@"

opts=()
[[ -n "${URL:-}" ]] && opts=(${opts[*]:-} --url $URL)
[[ -n "${USERNAME:-}" ]] && opts=(${opts[*]:-} --username $USERNAME)
[[ -n "${PASSWORD:-}" ]] && opts=(${opts[*]:-} --password $PASSWORD)
[[ -n "${APIKEY:-}" ]] && opts=(${opts[*]:-} --apikey $APIKEY)

rerun rundeck-acls:list ${opts[*]:-} --project $PROJECT

# Done. Exit with last command exit status.
exit $?

