# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Feb 23 16:01:50 PST 2016
#
#/ usage: rundeck-project:job-set-schedule  --url <${RUNDECK_URL:-}> [ --user <${RUNDECK_USER:=}>] [ --password <${RUNDECK_PASSWORD:=}>] [ --apikey <${RUNDECK_APIKEY:-}>]  --project <>  --job <>  --crontab <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --url) rerun_option_check $# $1; URL=$2 ; shift ;;
            --username) rerun_option_check $# $1; USERNAME=$2 ; shift ;;
            --password) rerun_option_check $# $1; PASSWORD=$2 ; shift ;;
            --apikey) rerun_option_check $# $1; APIKEY=$2 ; shift ;;
            --project) rerun_option_check $# $1; PROJECT=$2 ; shift ;;
            --job) rerun_option_check $# $1; JOB=$2 ; shift ;;
            --crontab) rerun_option_check $# $1; CRONTAB=$2 ; shift ;;
            # help option
            -|--*?) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [[ -z "$URL" ]] && { echo >&2 "missing required option: --url" ; return 2 ; }
    [[ -z "$PROJECT" ]] && { echo >&2 "missing required option: --project" ; return 2 ; }
    [[ -z "$JOB" ]] && { echo >&2 "missing required option: --job" ; return 2 ; }
    [[ -z "$CRONTAB" ]] && { echo >&2 "missing required option: --crontab" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export USERNAME
    export PASSWORD
    export APIKEY
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${URL:=}
: ${USERNAME:=}
: ${PASSWORD:=}
: ${APIKEY:=}
: ${PROJECT:=}
: ${JOB:=}
: ${CRONTAB:=}


