#!/usr/bin/env bash

#/ command: rundeck-project:list: "list existing projects"
#/ usage: rerun rundeck-project:list  --url <$RUNDECK_URL>  --username <$RUNDECK_USER> [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: URL USERNAME PASSWORD APIKEY


. $RERUN_MODULE_DIR/lib/functions.sh list || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}


set -o errexit -o nounset -o pipefail


rerun_options_parse "$@"

#
# Read authentication credentials
#
if [[ -n "${PASSWORD:-}" && -z "${APIKEY:-}" ]]
then
	COOKIES=$(rundeck_login "$URL" "$USERNAME" "$PASSWORD")
	CURLOPTS="$CURLOPTS -c $COOKIES -b $COOKIES"
elif [[ -z "${PASSWORD:-}" && -n "${APIKEY:-}" ]]; then
	CURLOPTS="$CURLOPTS -H X-Rundeck-Auth-Token:$APIKEY"
else
	rerun_die 2 "Either use --username <> --password <> ...or.. --apikey <>"
fi

CURL_OUT=$(mktemp -t curl.out.XXXXXXXXXX)
trap 'rm $CURL_OUT' EXIT; # cleanup on exit

if ! http_code=$(rundeck_curl -w "%{http_code}" -X GET ${URL}/api/1/projects -o $CURL_OUT)
then
	rerun_die 3 "curl request failed (exit code: $?)"
fi

case ${http_code:-} in
   	20*) : ;; # successful
	* ) rerun_die 3 "API error: ${URL}/api/1/projects" ;;
esac

xmlstarlet val -q $CURL_OUT

xmlstarlet sel -t -m '//project' -v name -n $CURL_OUT


# Done. Exit with last command exit status.
exit $?

