#!/usr/bin/env bash

#/ command: rundeck-project:acls-create: "create an aclpolicy"
#/ usage: rerun rundeck-project:acls-create [ --file <>] [ --aclpolicy <>]  --project <>  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: FILE ACLPOLICY PROJECT URL USERNAME PASSWORD APIKEY

. $RERUN_MODULE_DIR/lib/functions.sh acls-create || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

[[ ! -n $ACLPOLICY ]] && ACLPOLICY=$(basename $FILE)

opts=()
[[ -n "${URL:-}" ]] && opts=(${opts[*]:-} --url $URL)
[[ -n "${USERNAME:-}" ]] && opts=(${opts[*]:-} --username $USERNAME)
[[ -n "${PASSWORD:-}" ]] && opts=(${opts[*]:-} --password $PASSWORD)
[[ -n "${APIKEY:-}" ]] && opts=(${opts[*]:-} --apikey $APIKEY)
[[ -n "${GROUP:-}" ]] && opts=(${opts[*]:-} --group $GROUP)

rerun rundeck-acls:create ${opts[*]:-} --project $PROJECT --aclpolicy $ACLPOLICY --file $FILE 

# Done. Exit with last command exit status.
exit $?

