# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Mar  3 11:46:15 PST 2016
#
#/ usage: rundeck-project:job-import  --project <> [ --file <>]  --url <${RUNDECK_URL:-}> [ --user <${RUNDECK_USER:=}>] [ --password <${RUNDECK_PASSWORD:=}>] [ --apikey <${RUNDECK_APIKEY:-}>] [ --format <xml>] [ --dupe-option <create>] [ --uuid-option <preserve>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --project) rerun_option_check $# $1; PROJECT=$2 ; shift ;;
            --file) rerun_option_check $# $1; FILE=$2 ; shift ;;
            --url) rerun_option_check $# $1; URL=$2 ; shift ;;
            --username) rerun_option_check $# $1; USERNAME=$2 ; shift ;;
            --password) rerun_option_check $# $1; PASSWORD=$2 ; shift ;;
            --apikey) rerun_option_check $# $1; APIKEY=$2 ; shift ;;
            --format) rerun_option_check $# $1; FORMAT=$2 ; shift ;;
            --dupe-option) rerun_option_check $# $1; DUPE_OPTION=$2 ; shift ;;
            --uuid-option) rerun_option_check $# $1; UUID_OPTION=$2 ; shift ;;
            # help option
            -|--*?) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [[ -z "$FORMAT" ]] && FORMAT="$(rerun_property_get $RERUN_MODULE_DIR/options/format DEFAULT)"
    [[ -z "$DUPE_OPTION" ]] && DUPE_OPTION="$(rerun_property_get $RERUN_MODULE_DIR/options/dupe-option DEFAULT)"
    [[ -z "$UUID_OPTION" ]] && UUID_OPTION="$(rerun_property_get $RERUN_MODULE_DIR/options/uuid-option DEFAULT)"
    # Check required options are set
    [[ -z "$PROJECT" ]] && { echo >&2 "missing required option: --project" ; return 2 ; }
    [[ -z "$URL" ]] && { echo >&2 "missing required option: --url" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export USERNAME
    export PASSWORD
    export APIKEY
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${PROJECT:=}
: ${FILE:=}
: ${URL:=}
: ${USERNAME:=}
: ${PASSWORD:=}
: ${APIKEY:=}
: ${FORMAT:=}
: ${DUPE_OPTION:=}
: ${UUID_OPTION:=}


