# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Dec 29 12:21:39 PST 2015
#
#/ usage: rundeck-project:import  --project <> [ --file <>] [ --import-executions <true>] [ --import-config <true>] [ --import-acl <true>]  --url <${RUNDECK_URL:-}> [ --username <${RUNDECK_USER:-}>] [ --password <${RUNDECK_PASSWORD:-}>] [ --apikey <${RUNDECK_APIKEY:-}>] [ --preserve-jobuuid <true>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --project) rerun_option_check $# $1; PROJECT=$2 ; shift ;;
            --file) rerun_option_check $# $1; FILE=$2 ; shift ;;
            --import-executions) rerun_option_check $# $1; IMPORT_EXECUTIONS=$2 ; shift ;;
            --import-config) rerun_option_check $# $1; IMPORT_CONFIG=$2 ; shift ;;
            --import-acl) rerun_option_check $# $1; IMPORT_ACL=$2 ; shift ;;
            --url) rerun_option_check $# $1; URL=$2 ; shift ;;
            --username) rerun_option_check $# $1; USERNAME=$2 ; shift ;;
            --password) rerun_option_check $# $1; PASSWORD=$2 ; shift ;;
            --apikey) rerun_option_check $# $1; APIKEY=$2 ; shift ;;
            --preserve-jobuuid) rerun_option_check $# $1; PRESERVE_JOBUUID=$2 ; shift ;;
            # help option
            -|--*?) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [[ -z "$IMPORT_EXECUTIONS" ]] && IMPORT_EXECUTIONS="$(rerun_property_get $RERUN_MODULE_DIR/options/import-executions DEFAULT)"
    [[ -z "$IMPORT_CONFIG" ]] && IMPORT_CONFIG="$(rerun_property_get $RERUN_MODULE_DIR/options/import-config DEFAULT)"
    [[ -z "$IMPORT_ACL" ]] && IMPORT_ACL="$(rerun_property_get $RERUN_MODULE_DIR/options/import-acl DEFAULT)"
    [[ -z "$URL" ]] && URL="$(rerun_property_get $RERUN_MODULE_DIR/options/url DEFAULT)"
    [[ -z "$USERNAME" ]] && USERNAME="$(rerun_property_get $RERUN_MODULE_DIR/options/username DEFAULT)"
    [[ -z "$PASSWORD" ]] && PASSWORD="$(rerun_property_get $RERUN_MODULE_DIR/options/password DEFAULT)"
    [[ -z "$PRESERVE_JOBUUID" ]] && PRESERVE_JOBUUID="$(rerun_property_get $RERUN_MODULE_DIR/options/preserve-jobuuid DEFAULT)"
    # Check required options are set
    [[ -z "$PROJECT" ]] && { echo >&2 "missing required option: --project" ; return 2 ; }
    [[ -z "$URL" ]] && { echo >&2 "missing required option: --url" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export USERNAME
    export PASSWORD
    export APIKEY
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${PROJECT:=}
: ${FILE:=}
: ${IMPORT_EXECUTIONS:=}
: ${IMPORT_CONFIG:=}
: ${IMPORT_ACL:=}
: ${URL:=}
: ${USERNAME:=}
: ${PASSWORD:=}
: ${APIKEY:=}
: ${PRESERVE_JOBUUID:=}


